name: Deploy mBlog App

on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ secrets.GHCR_USERNAME}}/mblog-app-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
        
      - name: Restore dependencies
        run:  dotnet restore mBlog/mBlog.csproj

      - name: Build 
        run: dotnet build mBlog/mBlog.csproj --configuration Release

      - name: Publish
        run: dotnet publish mBlog/mBlog.csproj --configuration Release --output ./publish
      
      - name: Build Docker image
        run: docker build -t $IMAGE -f mBlog/Dockerfile ./mBlog
      
      - name: Push Docker image
        run: docker push $IMAGE